environment:
  VERSION: 1.14.1
  matrix:
    - PY_MAJOR_VER: 3
      PY_MINOR_VER: 7

install:
  - curl -fSsLO https://repo.anaconda.com/miniconda/Miniconda%PY_MAJOR_VER%-latest-Windows-x86_64.exe
  - Miniconda%PY_MAJOR_VER%-latest-Windows-x86_64.exe /InstallationType=JustMe /S /D=C:\miniconda64
  - set CONDA_ROOT="C:\miniconda64"
  - CALL %CONDA_ROOT%\Scripts\activate.bat
  - conda install -y constructor

build_script:
  - sed -e "s/@PY_MAJOR_VER@/%PY_MAJOR_VER%/g" -e "s/@PY_MINOR_VER@/%PY_MINOR_VER%/g" otconda\construct.yaml.in > otconda\construct.yaml
  - constructor -v otconda
  - otconda%PY_MAJOR_VER%-%VERSION%-Windows-x86_64.exe /S /D=C:\otconda
  - set CONDA_ROOT="C:\otconda"
  - CALL %CONDA_ROOT%\Scripts\activate.bat
  - python test_bundle.py

artifacts:
  - path: otconda*.exe
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Windows installer'
  provider: GitHub
  auth_token:
    secure: 4CkqK7ssPZsVuYY4gnYun8TlaVakivCHyw+EnT6z/KdoG3iTDcebHNdHQ+cYJFt+
  artifact: binary
  draft: false
  prerelease: false
  on:
    branch: /v.*/
    appveyor_repo_tag: true
